### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by hesen2006cn** [furqansiddiqui/bitcoind-rpc#1]
Problem 1
    - Installation request for furqansiddiqui/ethereum-rpc v0.1.3 -> satisfiable by furqansiddiqui/ethereum-rpc[v0.1.3].
    - furqansiddiqui/ethereum-rpc v0.1.3 requires furqansiddiqui/http-client dev-master -> satisfiable by furqansiddiqui/http-client[dev-master] but these conflict with your requirements or minimum-stability.
  Problem 2
    - furqansiddiqui/erc20-php v0.1.2 requires furqansiddiqui/ethereum-rpc >=0.1.1 -> satisfiable by furqansiddiqui/ethereum-rpc[v0.1.3].
    - furqansiddiqui/erc20-php 0.1.1 requires furqansiddiqui/ethereum-rpc dev-master -> satisfiable by furqansiddiqui/ethereum-rpc[dev-master] but these conflict with your requirements or minimum-stability.
    - furqansiddiqui/erc20-php 0.1.0 requires furqansiddiqui/ethereum-rpc dev-master -> satisfiable by furqansiddiqui/ethereum-rpc[dev-master] but these conflict with your requirements or minimum-stability.
    - furqansiddiqui/ethereum-rpc v0.1.3 requires furqansiddiqui/http-client dev-master -> satisfiable by furqansiddiqui/http-client[dev-master] but these conflict with your requirements or minimum-stability.
    - Installation request for furqansiddiqui/erc20-php @beta -> satisfiable by furqansiddiqui/erc20-php[0.1.0, 0.1.1, v0.1.2].

**Comment by furqansiddiqui** [comment]
First of all sorry for late reply, those errors are in regard to other lib so I will close here, I have already created appropriate releases on those libs so all should be ok.
